function sliders
% SLIDERS  Application for comparison of the RGB and HSV color spaces.
%          This file (sliders.m) also requires the files:
%
%             *  changecolor.m
%             *  showvalues.m
%             *  hidevalues.m
%
%          This application is written in January 1997 by J.Rydenius.
%

fig = gcf;
clf
% Setting the desired properties of the current figure.
set(fig,'Color',[0.7 0.7 0.7],'Position',[300,500,800,160], ...
    'Name','Comparing RGB and HSV color spaces.','Resize','off');


maxvalue=128;
X=20;Y=50;

% Drawing a frame around the RGB sliders.
rgb_frame = uicontrol(fig, ...
                  'Style','frame', ...
                  'Position',[X-10,Y-10,240,100]);

% Defining the RGB sliders.
rgb_sliders(1) = uicontrol(fig, ...
                  'Style','slider', ...
                  'Position',[X+45 Y+60 140 20], ...
                  'Min',0,'Max',maxvalue,'Value',maxvalue/2, ...
                  'UserData',maxvalue/2, ...
                  'Callback','changecolor(1)');
rgb_sliders(2) = uicontrol(fig, ...
                  'Style','slider', ...
                  'Position',[X+45 Y+30 140 20], ...
                  'Min',0,'Max',maxvalue,'Value',maxvalue/2, ...
                  'UserData',maxvalue/2, ...
                  'Callback','changecolor(2)');
rgb_sliders(3) = uicontrol(fig, ...
                  'Style','slider', ...
                  'Position',[X+45 Y 140 20], ...
                  'Min',0,'Max',maxvalue,'Value',maxvalue/2, ...
                  'UserData',maxvalue/2, ...
                  'Callback','changecolor(3)');

% Writing text labels to the left of the RGB sliders.
blue_label = uicontrol(fig, ...
                  'Style','text', ...
                  'Position',[X Y 40 20], ...
                  'String', 'Blue');
green_label = uicontrol(fig, ...
                  'Style','text', ...
                  'Position',[X Y+30 40 20], ...
                  'String', 'Green');
red_label = uicontrol(fig, ...
                  'Style','text', ...
                  'Position',[X Y+60 40 20], ...
                  'String', 'Red');

% Assigning the value fields to the right of the sliders.
rgb_values(1) = uicontrol(fig, ...
                  'Style','text', ...
                  'Position',[X+190 Y+60 30 20], ...
                  'String', num2str(get(rgb_sliders(1),'Value')));
rgb_values(2) = uicontrol(fig, ...
                  'Style','text', ...
                  'Position',[X+190 Y+30 30 20], ...
                  'String', num2str(get(rgb_sliders(1),'Value')));
rgb_values(3) = uicontrol(fig, ...
                  'Style','text', ...
                  'Position',[X+190 Y 30 20], ...
                  'String', num2str(get(rgb_sliders(1),'Value')));

% Initiating the hidden RGB values for the reference color.
real_rgb_values(1) = uicontrol(fig, ...
                  'Style','text', ...
                  'Position',[X+90 10 40 20], ...
                  'String', '0','Visible','off');
real_rgb_values(2) = uicontrol(fig, ...
                  'Style','text', ...
                  'Position',[X+140 10 40 20], ...
                  'String', '0','Visible','off');
real_rgb_values(3) = uicontrol(fig, ...
                  'Style','text', ...
                  'Position',[X+190 10 40 20], ...
                  'String', '0','Visible','off');


X=560;

% Drawing a frame around the HSV sliders.
hsv_frame = uicontrol(fig, ...
                  'Style','frame', ...
                  'Position',[X-10,Y-10,240,100]);

% Defining the HSV sliders.
hsv_sliders(1) = uicontrol(fig, ...
                  'Style','slider', ...
                  'Position',[X+45 Y+60 140 20], ...
                  'Min',0,'Max',maxvalue,'Value',maxvalue/2, ...
                  'UserData',maxvalue/2, ...
                  'Callback','changecolor(4)');
hsv_sliders(2) = uicontrol(fig, ...
                  'Style','slider', ...
                  'Position',[X+45 Y+30 140 20], ...
                  'Min',0,'Max',maxvalue,'Value',maxvalue/2, ...
                  'UserData',maxvalue/2, ...
                  'Callback','changecolor(5)');
hsv_sliders(3) = uicontrol(fig, ...
                  'Style','slider', ...
                  'Position',[X+45 Y 140 20], ...
                  'Min',0,'Max',maxvalue,'Value',maxvalue/2, ...
                  'UserData',maxvalue/2, ...
                  'Callback','changecolor(6)');

% Writing text labels to the left of the HSV sliders.
val_label = uicontrol(fig, ...
                  'Style','text', ...
                  'Position',[X Y 40 20], ...
                  'String', 'Val');
sat_label = uicontrol(fig, ...
                  'Style','text', ...
                  'Position',[X Y+30 40 20], ...
                  'String', 'Sat');
hue_label = uicontrol(fig, ...
                  'Style','text', ...
                  'Position',[X Y+60 40 20], ...
                  'String', 'Hue');

% Assigning the value fields to the right of the sliders.
hsv_values(1) = uicontrol(fig, ...
                  'Style','text', ...
                  'Position',[X+190 Y+60 30 20], ...
                  'String', num2str(get(hsv_sliders(1),'Value')));
hsv_values(2) = uicontrol(fig, ...
                  'Style','text', ...
                  'Position',[X+190 Y+30 30 20], ...
                  'String', num2str(get(hsv_sliders(1),'Value')));
hsv_values(3) = uicontrol(fig, ...
                  'Style','text', ...
                  'Position',[X+190 Y 30 20], ...
                  'String', num2str(get(hsv_sliders(1),'Value')));

% Initiating the hidden HSV values for the reference color.
real_hsv_values(1) = uicontrol(fig, ...
                  'Style','text', ...
                  'Position',[X-10 10 40 20], ...
                  'String', '0','Visible','off');
real_hsv_values(2) = uicontrol(fig, ...
                  'Style','text', ...
                  'Position',[X+40 10 40 20], ...
                  'String', '0','Visible','off');
real_hsv_values(3) = uicontrol(fig, ...
                  'Style','text', ...
                  'Position',[X+90 10 40 20], ...
                  'String', '0','Visible','off');


% Assigning a new proper colormap. First position is the reference
% color. Second is the current RGB color. And the third position in
% the colormap is the current HSV color, converted to RGB.
ref = rand(1,3);
rgb = [0.5,0.5,0.5];
hsv = hsv2rgb([0.5,0.5,0.5]);
colormap([ref;rgb;hsv]);


% Reference color field.
ref_col = axes('Parent',fig,'Units','pixels', ...
               'Position',[350,Y-10,100,100]);
image(1) % The image has only the size of one pixel, assigned to colormap pos 1.
set(ref_col,'Visible','off');

% RGB color field.
rgb_col = axes('Parent',fig,'Units','pixels', ...
               'Position',[270,Y-10,80,100]);
image(2) % The image has only the size of one pixel, assigned to colormap pos 2.
set(rgb_col,'Visible','off');

% HSV color field.
hsv_col = axes('Parent',fig,'Units','pixels', ...
               'Position',[450,Y-10,80,100]);
image(3) % The image has only the size of one pixel, assigned to colormap pos 3.
set(hsv_col,'Visible','off');


% New-button.
new_button = uicontrol(fig, ...
                       'Style','push', ...
                       'Position',[370,5,60,30], ...
                       'String','New','CallBack',[ ...
                       'map=colormap;','colormap([rand(1,3);map(2:size(map,1),:)]);', ...
                       'hidevalues']);

% Close-button.
new_button = uicontrol(fig, ...
                       'Style','push', ...
                       'Position',[700,5,70,30], ...
                       'String','Close','CallBack','close(gcf)');

% Show RGB button.
new_button = uicontrol(fig, ...
                       'Style','push', ...
                       'Position',[280,5,80,30], ...
                       'String','Show RGB','CallBack', 'showvalues(''rgb'')');

% Show HSV button.
new_button = uicontrol(fig, ...
                       'Style','push', ...
                       'Position',[440,5,80,30], ...
                       'String','Show HSV','CallBack','showvalues(''hsv'')');

% Saving UserData matrix, so the objects can be referenced later.
set(fig,'UserData',[rgb_sliders hsv_sliders rgb_values hsv_values ...
                    real_rgb_values real_hsv_values]);

